# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TigerEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TigerEx
  
  # UI Framework
  pod 'SwiftUI'
  
  # Networking
  pod 'Alamofire', '~> 5.8'
  pod 'Starscream', '~> 4.0' # WebSocket
  
  # JSON Parsing
  pod 'SwiftyJSON', '~> 5.0'
  
  # Image Loading and Caching
  pod 'Kingfisher', '~> 7.0'
  
  # Charts and Graphs
  pod 'Charts', '~> 4.1'
  pod 'DGCharts', '~> 5.0'
  
  # Database
  pod 'RealmSwift', '~> 10.0'
  pod 'SQLite.swift', '~> 0.14'
  
  # Keychain and Security
  pod 'KeychainAccess', '~> 4.2'
  pod 'CryptoSwift', '~> 1.8'
  
  # Biometric Authentication
  pod 'LocalAuthentication'
  
  # QR Code Scanner
  pod 'CodeScanner', '~> 2.3'
  
  # Camera and Photo
  pod 'AVFoundation'
  pod 'Photos'
  
  # Push Notifications
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  
  # Location Services
  pod 'CoreLocation'
  
  # Animations
  pod 'lottie-ios', '~> 4.3'
  pod 'Spring', '~> 1.0'
  
  # Utilities
  pod 'SwiftDate', '~> 7.0'
  pod 'PhoneNumberKit', '~> 3.7'
  pod 'CountryPickerView', '~> 3.3'
  
  # Development Tools
  pod 'SwiftLint', '~> 0.52'
  pod 'SwiftFormat/CLI', '~> 0.52'
  
  target 'TigerExTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 7.0'
    pod 'Nimble', '~> 12.0'
    pod 'OHHTTPStubs/Swift', '~> 9.1'
  end

  target 'TigerExUITests' do
    # Pods for UI testing
  end
end

# Post install configuration
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.9'
      
      # Fix for Xcode 15
      if config.name == 'Debug'
        config.build_settings['OTHER_SWIFT_FLAGS'] = '-Xfrontend -warn-long-expression-type-checking=100'
      end
      
      # Disable code signing for pods
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end