# TigerEx Wallet API
wallet_create:
  script:
    - ADDRESS=$(echo "0x$(openssl rand -hex 20)")
    - SEED="abandon ability able about above absent absorb abstract absurd abuse access accident account accuse achieve acid acoustic acquire across act action actor actress actual adapt add adjust admin admit adult advance advice aerobic affair afford afraid again age agency agent agree ahead aim air airport alarm album alcohol alien alike alive allow alone along alpha already also alter always amazing among amount analyze ancient angle angry animal anniversary announce another answer antenna anxiety any apart apology appear apple approve april aqua arabian architecture area argue arise armed armor army around arrange"
    - echo "address=$ADDRESS" >> $GITHUB_OUTPUT
