name: CI

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Removed npm caching as we don't track package-lock.json files

      - name: Install dependencies
        run: npm install

      - name: Format code
        run: npm run format

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
